/* Sample IDL file */

struct Position {
  double x;
  double y;
  double z;
};

struct Distance {
  double dx;
  double dy;
  double dz;
};

struct ArrayTest {
  int num;
  unsigned long longuns [3];
  unsigned long doubleuns [3];
};
