stages:
  - build

before_script:
  - ls
  
build_job:
  stage: build
  script:
  - make
  - ./test/ci.sh

  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 21 days
    paths:
     - ci
